<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.Cris" Version="0.43.2" />
    <PackageReference Include="CK.Cris.DeviceModel" Version="14.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.IO.DeviceModel.ByTopic\CK.IO.DeviceModel.ByTopic.csproj" />
  </ItemGroup>
</Project>