<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.Testing.NUnit" Version="15.0.0--ci.6" />
    <PackageReference Include="CK.Testing.StObjEngine" Version="33.0.0--ci.13" />
    <PackageReference Include="CK.Cris.BackgroundExecutor" Version="0.43.0--ci.7" />
    <PackageReference Include="CK.Cris.Executor.Engine" Version="0.43.0--ci.7" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CK.DeviceModel.ByTopic\CK.DeviceModel.ByTopic.csproj" />
  </ItemGroup>
</Project>